title: Zero's Dev Blog
logo: "images/logo.svg" # You can add own logo image.
description: iOS, ML, 서버, 알고리즘 등을 학습한 것을 공유하고, 매일매일 TIL(Today I Learned)을 남기는 개발 블로그입니다.
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://zerodev.github.io" # The base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author:
  name: zero
  bio: 제로라고 합니다. iOS와 기계학습에 관심이 많습니다.

# Contact links
twitter: # Add your Twitter handle
facebook: # Add your Facebook handle
dribbble: # Add your Dribbble handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle
email: yyi9647@gmail.com # Add your Email address

# Hero Section
hero: true # To enable the section hero, use the value true. To turn off use the value false.
hero-title: Zero's Dev Blog # Add your hero title
hero-subtitle: iOS, 알고리즘 등을 학습한 것을 공유하고, TIL(Today I Learned)을 남기는 개발 블로그입니다.
hero-image: images/hero.jpg # Add background image in section hero

# Footer
footer-image: images/footer.jpg # Add background image in footer

# Comment Section (Disqus)
disqus-identifier: zero # Add your shortname for Disqus Comment. For example mr-brown

# Google Analytics
google-analytics: "UA-154969093-1" # Add your identifier. For example UA-99631805-1.

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 4
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed
